### ISSUE TITLE
Support 'norg' file format

### ISSUE THREAD

**Issue by atidyshirt** [plainorg/plainorg#13]
Support for `neorg` if possible:

Its an `neovim` interpretation of org mode: https://github.com/nvim-neorg/neorg

Option One: allow for the use of different extensions and assume that it is to be interpreted as an org file
Option Two: support `norg` (could be a lot of work, I am happy with option 1)

**Comment by xenodium** [comment]
Thanks for filing! I'm not familiar with norg markup but if it's syntax is equivalent to org's, I can allowlist the extension so you can open it in Plain Org. Would that help?

**Comment by atidyshirt** [comment]
Thanks for the reply, the syntax is not quite equivalent, but is very similar, that would help as an intermitted step to allow us to use the app and just accept that code blocks and a few minor things won't render correctly.

If you did try to go into the relm of full suppprt for norg documents, something to note is that currently the filetype is specific to neovim, however the next major version of the project aims to change this, I am not exactly sure how this will be exposed yet, but am happy to do some research and get back to you on that if this is something you would consider supportong?

> note the implementation of this would have to be after the next major release

**Comment by xenodium** [comment]
It would be hard for me to evaluate how useful the partial support would be, though I'm happy to share a special build via TestFlight and you can give it a go? I'd need an email address to send the TestFlight invite.

**Comment by atidyshirt** [comment]
yes that would be fine, you can send a test build to jordanpyott@gmail.com, I can assess how it works and if it's feasible/worth supporting
